// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "cff8493a-29e3-4070-af70-2a1fc7724c27");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1617234540);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1617314673);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1617315118);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1617314758);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1617239050);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1617239170);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1617238930);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1617234663);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 74526);
user_pref("browser.cache.disk.capacity", 983040);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1612370848);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{47cafcf2-6abd-46a5-833c-7c02ce95838b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1617238916787");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1617240717787");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1617235283074");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1617256883074");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210119174753");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1617314682");
user_pref("browser.slowStartup.averageTime", 50125);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210119174753");
user_pref("browser.startup.homepage_override.mstone", "78.7.0");
user_pref("browser.startup.lastColdStartupCheck", 1617314660);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.tipShownCount.searchTip_redirect", 3);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "78.7.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "7058608791eb4319a3a920f5d0ee0b8c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1617234599);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210119174753");
user_pref("extensions.lastAppVersion", "78.7.0");
user_pref("extensions.lastPlatformVersion", "78.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"55a4033b-7e3f-4780-b0a3-7dd12d78d8e7\",\"formautofill@mozilla.org\":\"2f5cd287-ae9d-43e6-b05a-176e1c67823d\",\"screenshots@mozilla.org\":\"cac85783-f286-49cb-8e59-c2eb5932b5cc\",\"webcompat-reporter@mozilla.org\":\"4ceaed5f-2b00-4239-816e-bb3f1a16091c\",\"webcompat@mozilla.org\":\"9b2eb068-8117-4aba-abe9-275f3e9552e7\",\"default-theme@mozilla.org\":\"71e8462c-1c88-4a0c-b003-2efa0c8fa74b\",\"google@search.mozilla.org\":\"4c8c8802-ae7e-4334-9ced-ec75b69c72e7\",\"amazondotcom@search.mozilla.org\":\"a8fec754-80d8-4aae-a256-41e9d1b117d1\",\"wikipedia@search.mozilla.org\":\"8115bceb-c3f7-4312-b90f-37f86c2dc0e7\",\"bing@search.mozilla.org\":\"5cd9f3fc-e657-41c8-b07f-829f07f1244b\",\"ddg@search.mozilla.org\":\"a8580db7-79fe-40f9-bc47-2a55fdc26310\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20210119174753");
user_pref("media.gmp-manager.lastCheck", 1617234578);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1617358684);
user_pref("security.remote_settings.intermediates.checked", 1617358684);
user_pref("security.sandbox.content.tempDirSuffix", "fefa17d2-d378-4d76-a074-f841c3fa833f");
user_pref("security.sandbox.plugin.tempDirSuffix", "6b4e624c-7b57-419b-afa6-bd9bbad644d1");
user_pref("services.blocklist.addons-mlbf.checked", 1617358684);
user_pref("services.blocklist.gfx.checked", 1617358684);
user_pref("services.blocklist.pinning.checked", 1617358684);
user_pref("services.blocklist.plugins.checked", 1617358684);
user_pref("services.settings.clock_skew_seconds", -43861);
user_pref("services.settings.last_etag", "\"1617321679887\"");
user_pref("services.settings.last_update_seconds", 1617358684);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1617358684);
user_pref("services.settings.main.cfr-fxa.last_check", 1617358684);
user_pref("services.settings.main.cfr.last_check", 1617358684);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1617358684);
user_pref("services.settings.main.hijack-blocklists.last_check", 1617358684);
user_pref("services.settings.main.language-dictionaries.last_check", 1617358684);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1617358684);
user_pref("services.settings.main.public-suffix-list.last_check", 1617358684);
user_pref("services.settings.main.search-config.last_check", 1617358684);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1617358684);
user_pref("services.settings.main.sites-classification.last_check", 1617358684);
user_pref("services.settings.main.tippytop.last_check", 1617358684);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1617358684);
user_pref("services.settings.main.whats-new-panel.last_check", 1617358684);
user_pref("services.settings.security.onecrl.checked", 1617358684);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1617314613);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210119174753");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
